export type Lang = 'he' | 'en'

const strings = {
  he: {
    appName: 'ReleaseRadar',
    nav: {
      toggleLang: 'EN',
    },
    buttons: {
      newRelease: '+ פרויקט חדש',
      save: 'שמור',
      cancel: 'ביטול',
      toggleLang: 'EN',
      addTrack: '+ הוסף שיר',
      addTask: 'הוסף',
      addMedia: '+ הוסף גוף מדיה',
      addLink: 'הוסף לינק',
      back: '← כל הפרויקטים',
    },
    labels: {
      titleHe: 'שם הפרויקט (עברית)',
      titleEn: 'שם הפרויקט (אנגלית)',
      releaseDate: 'תאריך יציאה',
      status: 'סטטוס',
      projectType: 'סוג פרויקט',
      tracks: 'שירים',
      trackName: 'שם השיר',
      taskTitle: 'כותרת משימה',
      dueDate: 'תאריך יעד',
      notes: 'הערות',
    },
    tabs: {
      assets: 'נכסים',
      tasks: 'משימות',
      submissions: 'הגשות',
    },
    status: {
      draft: 'טיוטה',
      scheduled: 'מתוכנן',
      released: 'יצא',
    },
    projectType: {
      single: 'סינגל',
      ep: 'EP',
      album: 'אלבום',
    },
    submissionStatus: {
      not_sent: 'טרם נשלח',
      submitted: 'הוגש',
      waiting: 'ממתין לתשובה',
      playlisted: 'הוכנס לפלייליסט ✓',
      rejected: 'נדחה',
    },
    page: {
      title: 'הפרויקטים שלי',
      subtitle: 'ניהול ריליסים, נכסים והגשות',
      emptyTitle: 'אין פרויקטים עדיין',
      emptySubtitle: 'צרי את הפרויקט הראשון שלך',
    },
    detail: {
      assetsProgress: 'מוכנים',
      assetsOf: 'מתוך',
      assetsReady: 'נכסים מוכנים',
      tracks: 'שירים',
      completedSection: 'משימות שהושלמו',
      showCompleted: 'הצג',
      hideCompleted: 'הסתר',
      overdue: 'באיחור',
      noTasks: 'אין משימות עדיין',
      linkPlaceholder: 'הדביקי URL',
    },
    modal: {
      newProject: 'פרויקט חדש',
      selectType: 'בחרי סוג פרויקט',
      addTracksHint: 'הוסיפי את שמות השירים',
    },
    loading: 'טוען...',
  },
  en: {
    appName: 'ReleaseRadar',
    nav: {
      toggleLang: 'עב',
    },
    buttons: {
      newRelease: '+ New Project',
      save: 'Save',
      cancel: 'Cancel',
      toggleLang: 'עב',
      addTrack: '+ Add Track',
      addTask: 'Add',
      addMedia: '+ Add Outlet',
      addLink: 'Add Link',
      back: '← All Projects',
    },
    labels: {
      titleHe: 'Project Name (Hebrew)',
      titleEn: 'Project Name (English)',
      releaseDate: 'Release Date',
      status: 'Status',
      projectType: 'Project Type',
      tracks: 'Tracks',
      trackName: 'Track Name',
      taskTitle: 'Task Title',
      dueDate: 'Due Date',
      notes: 'Notes',
    },
    tabs: {
      assets: 'Assets',
      tasks: 'Tasks',
      submissions: 'Submissions',
    },
    status: {
      draft: 'Draft',
      scheduled: 'Scheduled',
      released: 'Released',
    },
    projectType: {
      single: 'Single',
      ep: 'EP',
      album: 'Album',
    },
    submissionStatus: {
      not_sent: 'Not Sent',
      submitted: 'Submitted',
      waiting: 'Awaiting Response',
      playlisted: 'Playlisted ✓',
      rejected: 'Rejected',
    },
    page: {
      title: 'My Projects',
      subtitle: 'Manage releases, assets and submissions',
      emptyTitle: 'No projects yet',
      emptySubtitle: 'Create your first project',
    },
    detail: {
      assetsProgress: 'ready',
      assetsOf: 'of',
      assetsReady: 'assets ready',
      tracks: 'tracks',
      completedSection: 'Completed Tasks',
      showCompleted: 'Show',
      hideCompleted: 'Hide',
      overdue: 'overdue',
      noTasks: 'No tasks yet',
      linkPlaceholder: 'Paste URL',
    },
    modal: {
      newProject: 'New Project',
      selectType: 'Select project type',
      addTracksHint: 'Add track names',
    },
    loading: 'Loading...',
  },
}

export type Strings = typeof strings['he']
export default strings
